### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by TheMusicMeister** [currency-cop/currency-cop#105]
When opening the program, it asks for the session id as expected, but when the POESESSID is pasted into the field, the Login button does nothing.  It clicks and stays faded for a few seconds, but never progresses to the next screen.

**Comment by TiiaAurora** [comment]
Same problem here. I also refreshed my Session ID but it didn't fix it.

**Comment by robmart** [comment]
Same issue

**Comment by TyChild** [comment]
Same issue here!

**Comment by syrm** [comment]
Same issue

**Comment by jtuc** [comment]
Same issue. Checking the logs folder, it looks like this is due to cloudflare - I get `[20:10:01] [WARN] [API] 503 status response for [https://www.pathofexile.com/login]`, followed by the html for cloudflare's ddos protection page.

Is everyone else getting the same message in `%APPDATA%/currency-cop/Logs`?

**Comment by syrm** [comment]
Yes same message

**Comment by mekhami** [comment]
You don't need to spam 'same issue' over and over, leave a reaction on the original post. (I realize not all of you are probably programmers/regular github users, but this is the proper etiquette for issues like this.)

**Comment by daniele-salvagni** [comment]
GGG said they placed the login page behind Cloudflare, they will soon allow login via OAuth.

**Comment by jamesbrooks** [comment]
Disabling checking if the Session ID is still valid (the only post that needs to hit /login) resolves this issue.

I have submitted a PR for this here: https://github.com/currency-cop/currency-cop/pull/106

Until it is merged feel free to use my fork here with that change applied: https://github.com/jamesbrooks/currency-cop

**Comment by Innomen** [comment]
> You don't need to spam 'same issue' over and over, leave a reaction on the original post. (I realize not all of you are probably programmers/regular github users, but this is the proper etiquette for issues like this.)

Thank you, I did not know that.

**Comment by GoldenGonzo** [comment]
> 
> 
> Disabling checking if the Session ID is still valid (the only post that needs to hit /login) resolves this issue.
> 
> I have submitted a PR for this here: #106
> 
> Until it is merged feel free to use my fork here with that change applied: https://github.com/jamesbrooks/currency-cop

I didn't see an installation file on your page?  Most of us aren't programmers, we're just here on GitHub solely to use Currency Cop.  We don't know what to do with the raw files you're having us download.

**Comment by jamesbrooks** [comment]
That is fair enough.

In that case it'd likely be best to wait until @nijikokun merges that Pull Request, rebuilds and uploads a new release of the app as I do not have Docker installed locally (required to build this Electron app).

**Comment by Zwirni23** [comment]
> 
> 
> That is fair enough.
> 
> In that case it'd likely be best to wait until @nijikokun merges that Pull Request, rebuilds and uploads a new release of the app as I do not have Docker installed locally (required to build this Electron app).

So us non-programmers can install "Docker" and create the app? Or could you please explain in a few words what we should do with your build? 
Thanks in advance.

**Comment by jamesbrooks** [comment]
There are two things you could do to get a copy running with my fork.

First you could install node.js, and with that installed run the commands listed in the readme (specifically `npm install` and `npm run dev`), this will let you run a development copy using the source code itself.

Secondly you can try and build the source code into a final product (the electron app) which uses docker from a quick look at the build.sh file, aside from getting docker up and running I do not know if there are any requirements for building this app (I am unfamiliar with Electron apps).

**Comment by GoldenGonzo** [comment]
> 
> 
> There are two things you could do to get a copy running with my fork.
> 
> First you could install node.js, and with that installed run the commands listed in the readme (specifically `npm install` and `npm run dev`), this will let you run a development copy using the source code itself.
> 
> Secondly you can try and build the source code into a final product (the electron app) which uses docker from a quick look at the build.sh file, aside from getting docker up and running I do not know if there are any requirements for building this app (I am unfamiliar with Electron apps).

I just had my programmer friend try for the last hour to try to create an .exe from your fork, with no success.  I'm not sure how the layman is supposed to succeed.

**Comment by jamesbrooks** [comment]
Then I imagine they'll have just as much difficulty creating a build from this repository as the only difference between this repository and my fork is the removal of six lines of code; nothing about the build process has been changed.

The layman would be best waiting until this change has been merged and the project owner has performed a build and released the executable as stated previously (this is not something I will be doing as I am unfamiliar with building Electron apps and have no interest in setting up a development environment to perform this build).

**Comment by Innomen** [comment]
To whom it may concern Acquisition recently updated to address this very issue. Apparently it's because poe changed how things are done to harden itself vs ddos attack.

**Comment by syrm** [comment]
I builded the code of @jamesbrooks with the fix : https://www.bouh.org/CurrencyCop-2.0.0-beta.14.exe

**Comment by Innomen** [comment]
> I builded the code of @jamesbrooks with the fix : https://www.bouh.org/CurrencyCop-2.0.0-beta.14.exe

And it works, thank you.

**Comment by GoldenGonzo** [comment]
> 
> 
> I builded the code of @jamesbrooks with the fix : https://www.bouh.org/CurrencyCop-2.0.0-beta.14.exe

I love you!  It works, thank you.

**Comment by Losar22** [comment]
Using that fix, I now get "Cannot read property '1' of null" instead of nothing, progress.

Re-logging into pathofexile.com resolved issue.

**Comment by syrm** [comment]
With this fix there is not SESSION check anymore, so you can have a wrong session and be "logged" in application. In such case you'll probably have error like this. Logout/Login on PathOfExile.com and get the new SESSION should be ok like you said.

**Comment by veenarm** [comment]
Yeh, I had the same issue with my discord bot scraping only login content...
used POESESS and didn't login now rather than creds :|

**Comment by guatrad** [comment]
When trying to log in I'm getting this errror:

🔥 This is fine: Na.filter is not a function

**Comment by syrm** [comment]
@guatrad give me the log of this error

**Comment by syrm** [comment]
I made a better fix to this problem, you can download the client here : http://currency-cop.bouh.org/CurrencyCop-2.0.0-beta.15.exe

With this fix, the SESSION is checked.
The modification can be found here : https://github.com/currency-cop/currency-cop/pull/107

**Comment by nijikokun** [comment]
Apologies, I have recently moved (new home) and resettling, will release a new build tonight.

**Comment by Innomen** [comment]
> Apologies, I have recently moved (new home) and resettling, will release a new build tonight.

Gz on the new digs :) Welcome back.

**Comment by loper** [comment]
still broken

**Comment by mekhami** [comment]
Just a fair warning, and I'm not trying to imply that this has happened here, but you should be very cautious about downloading and using .exe's from untrusted sources. The people above *could* (not saying they DID) inject malicious code into the existing currency cop code, package it as a .exe, and distribute it and nobody would be the wiser.

Take sane precautions, and if you don't know what/how to do that, you should probably avoid using it until the official release is done.

**Comment by berserkingyadis** [comment]
@syrm the build you linked doesnt work, i cant even add a portfolio or add a second tab to it.

the first link you posted works (doesnt price map stash tho (https://www.bouh.org/CurrencyCop-2.0.0-beta.14.exe))

**Comment by syrm** [comment]
I tested right now without any problem, someone else have the same problem ?

**Comment by GoldenGonzo** [comment]
> 
> 
> Apologies, I have recently moved (new home) and resettling, will release a new build tonight.

Congratulations on the new home.  Is that new build still coming?

**Comment by RamyGildenberg** [comment]
> I tested right now without any problem, someone else have the same problem ?

yeah , cant get maps priced as well, plus having some kind of rubberbanding effect with the scrolling , everytime i scroll with the mouse wheel, it returns to the original spot a second or two

**Comment by leet0rz** [comment]
Still not able to log in here.

**Comment by RamyGildenberg** [comment]
> Still not able to log in here.

download from the link in the comments

**Comment by xpanterx** [comment]
I know this is free, and I'm not complaining, but since it doesn't work anymore it would be helpful with a message in big letters on https://www.pathofexile.com/forum/view-thread/1989935/page/1 saying something like "Currently not working!" so people don't waste their time, thanks!

**Comment by RamyGildenberg** [comment]
It is working if you download the fixed version from syrm,although it dosn't detect maps.

**Comment by leet0rz** [comment]
I dont really want to download anything unless its from the creator itself.

**Comment by syrm** [comment]
About map price, it's seems to be a problem on GGG Api.
Do you know any other software with map price ?

**Comment by CheeseOfTruth** [comment]
Is there something wrong with the Prices? I mean it shows me for example "Perfect Fossils" worth 8c, while they are going for 2c.

**Comment by syrm** [comment]
About wrong pricing, i tried to fix this with this PR : https://github.com/currency-cop/currency-cop/pull/108
You can test it on this build and told me if everything is ok : http://currency-cop.bouh.org/CurrencyCop-2.0.0-beta.16.exe

**Comment by CheeseOfTruth** [comment]
Prices seem to be Accurate now. Thanks

**Comment by GoldenGonzo** [comment]
Is the original CurrencyCop still broken?

**Comment by syrm** [comment]
Yes, you need to take my version until the author of CurrencyCop release my fix

**Comment by asdf337** [comment]
I went over to using Exilence, its pretty much the same stuff with some
more features added, group play and so on.

**Comment by nijikokun** [comment]
Released new version with the fixes, currently working on a variant with OAuth.
