### ISSUE TITLE
no scarab support?

### ISSUE THREAD

**Issue by chris-thomas-dev** [currency-cop/currency-cop#115]
Tried to view my fragment tab and scarabs values not calculated

**Comment by chris-thomas-dev** [comment]
made a patch, just trying to work out how to push a branch

**Comment by chris-thomas-dev** [comment]
From ae1af3ae9341b0c3568dc940d1a8c5e4177d4593 Mon Sep 17 00:00:00 2001
From: Chris Thomas <chris.john.thomas@gmail.com>
Date: Sat, 10 Aug 2019 10:50:18 +1000
Subject: [PATCH] scarab support

---
 src/api.js                   | 1 +
 src/classes/reportbuilder.js | 2 ++
 src/constants.js             | 2 +-
 3 files changed, 4 insertions(+), 1 deletion(-)

diff --git a/src/api.js b/src/api.js
index 33c5e58..c955f26 100644
--- a/src/api.js
+++ b/src/api.js
@@ -213,6 +213,7 @@ exports.ItemRateTypes = {
   fragment: exports.GetFragmentOverview,
   card: exports.GetDivCardOverview,
   map: exports.GetMapOverview,
+  scarab: exports.GetScarabOverview,
   gem: exports.GetSkillGemOverview,
   unique_map: exports.GetUniqueMapOverview,
   unique_jewel: exports.GetUniqueJewelOverview,
diff --git a/src/classes/reportbuilder.js b/src/classes/reportbuilder.js
index 2e5ef6b..f54baa9 100644
--- a/src/classes/reportbuilder.js
+++ b/src/classes/reportbuilder.js
@@ -10,6 +10,7 @@ import {
   GetCharacters,
   GetLeagueStashTab,
   GetCurrencyOverview,
+  GetScarabOverview,
   GetEssenceOverview,
   GetFragmentOverview,
   GetDivCardOverview,
@@ -198,6 +199,7 @@ class ReportBuilder {
       .then(() => this.notice('Fetching currency rates...'))
       .then(() => (this.data.rates = []))
       .then(() => this.fetchCurrencyRates('currency', GetCurrencyOverview))
+      .then(() => this.fetchScarabRates('scarab', GetScarabOverview))
       .then(() => this.fetchRate('essence', GetEssenceOverview))
       .then(() => this.fetchFragmentRates('fragment', GetFragmentOverview))
       .then(() => this.fetchDivCardRates('card', GetDivCardOverview))
diff --git a/src/constants.js b/src/constants.js
index ac226d4..4759b63 100644
--- a/src/constants.js
+++ b/src/constants.js
@@ -21,7 +21,7 @@ export const NINJA_ITEM_URL                       = 'https://poe.ninja/api/data/
 
 export const NINJA_CURRENCY_OVERVIEWS             = [ 'Currency', 'Fragment' ]
 
-export const NINJA_ITEM_OVERVIEWS                 = [ 'Map', 'Essence', 'SkillGem',
+export const NINJA_ITEM_OVERVIEWS                 = [ 'Map', 'Essence', 'SkillGem', 'Scarab',
                                                       'UniqueMap', 'UniqueJewel', 'UniqueFlask',
                                                       'UniqueArmour', 'UniqueWeapon', 'UniqueAccessory',
                                                       'Fossil', 'Resonator', 'Prophecy'
-- 
2.7.4.windows.1

**Comment by chris-thomas-dev** [comment]
tried to commit but it looks like i put it on a fork? sorry github newb

https://github.com/SoulOfMinsc/currency-cop.git

**Comment by Masterdo** [comment]
The next step is to open a Pull Request between that branch on your fork and master on the main repository here. But this project seems to be rather dead, I doubt it would get merged. Still, give that a try first.

**Comment by nijikokun** [comment]
Released 2.0.0-beta.16! Closing. Thanks @dinols !
