### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by seop11** [currency-cop/currency-cop#116]
I have kitava error.

it was worked at 12 hours ago
![image](https://user-images.githubusercontent.com/54226213/63219949-cdf3e580-c1b7-11e9-8b30-e2f43e52f828.png)

**Comment by JeongRakkyu** [comment]
same issue

**Comment by gotex007** [comment]
Me too. Weird. Mine's for "essence item rates", but yeah.

**Comment by nijikokun** [comment]
Released 2.0.0-beta.16! Closing. Thanks @dinols !
