### ISSUE TITLE
Item recognition issue?

### ISSUE THREAD

**Issue by Jhyper11** [currency-cop/currency-cop#117]
To sum up the problem, I have 2 tabs full of random loot gear/gems/fossils and about 1/3 of the items actually pop up in Currency Cop. Not sure if this is intended or a bug...but still quite annoying. 

I've double checked the tabs are selected, I've placed other items in the tabs and have had them pop up, just for some reason certain items don't show up..

**Comment by nijikokun** [comment]
Released 2.0.0-beta.16! Closing. Thanks @dinols !
