### ISSUE TITLE
Isn't working since Blight started.

### ISSUE THREAD

**Issue by gotex007** [currency-cop/currency-cop#118]
It just gets stuck on a portfolio "updating".
![YElQa9e](https://user-images.githubusercontent.com/8534139/64492342-ff088880-d240-11e9-957f-fccc93d2e09f.png)

Other programs like Exilence are working fine so why not Currency Cop? I prefer Currency Cop's simplicity.

**Comment by gotex007** [comment]
Oh. Sometimes it shows "waiting for data" instead.
![a4YkXd7](https://user-images.githubusercontent.com/8534139/64492728-28c3ae80-d245-11e9-944a-ac340b9ea8bd.png)

It does it for standard too so it isn't a league issue.

**Comment by dinols** [comment]
Hello guys, i created a pull request to fix the current issue and i'm waiting for a review.
I also added support for incubators, oils, and scarabs.

While the pull request is getting reviewed, you can download a temporary version here :
https://github.com/dinols/currency-cop/releases/tag/2.0.0-beta.16

Would love some feedbacks regarding gem pricing (quality, level ...)

**Comment by WafuRuns** [comment]
@dinols Would gladly give you feedback, unfortunately, the same issue is present for your version. It gets stuck just as this one.

**Comment by dinols** [comment]
@KawaiiWafu Works fine for me and some friends, did you try to uninstall the last version before installing this one ?
Can you provide screenshots ? How many stash did you select in your portfolio ?

**Comment by gotex007** [comment]
Your version works perfectly dinols. I'm so glad I can use Curency Cop again instead of Exilence; it's just simpler. All I did was just install it over top the original.

**Comment by veenarm** [comment]
Maybe it gets stuck with the new delve tab? @KawaiiWafu

**Comment by hatani** [comment]
Having same issue, owning delve tab too if that matters.

**Comment by nijikokun** [comment]
Released 2.0.0-beta.16! Closing. Thanks @dinols !
