### ISSUE TITLE
Lightpoacher 261c instead of 1c, got only 1abys socket

### ISSUE THREAD

**Issue by peichhorndev** [currency-cop/currency-cop#28]
Lightpoacher is calculated wrong.
261c is the price on poe.ninja for 2 abys sockets, mine got only 1.
is there anything i could to to correct this? could only move it to a stash that is not tracked

**Comment by AngryRoleplayer** [comment]
Same for Bubonic Trail and any other 1-socket abyssal items. All treated as 2-sockets.

**Comment by nijikokun** [comment]
See #34
