### ISSUE TITLE
cannot remove broken reports

### ISSUE THREAD

**Issue by nerdc0re-net** [currency-cop/currency-cop#29]
There is no possibility to remove/delete broken reports, nor is there any information where on my disk these application-information is stored & those file are not removed when uninstalling the application.

**Comment by jrettsch** [comment]
I have the same issue in the latest beta "CurrencyCop-1.2.5-beta1-x64.exe"

**Comment by mkwarr** [comment]
I am having the same issue.  Please let me know if I have to remove some files or what needs to be done.  Thank you.

**Comment by nerdc0re-net** [comment]
I actually deleted the whole application from my disk, it just does not seem to get any support at all, haven't got any response on that issue here or in the official forums.

**Comment by nijikokun** [comment]
See #34
