### ISSUE TITLE
Certain items are not being recognized

### ISSUE THREAD

**Issue by MediEvilHero** [currency-cop/currency-cop#36]
Items such as:
- Essences;
- Offerings to the Goddess;
- Sacrifice fragments;
- Divine Vessels;
- Maps;
- Uniques with Abyssal sockets.
All tested with my stash in Bestiary Softcore. Tried putting them both in normal tabs and in special tabs, when applicable (except for maps, since map tab isn't picked up by stash API iirc).

**Comment by nijikokun** [comment]
Have you tried using https://github.com/currency-cop/currency-cop/issues/34 ?

**Comment by nijikokun** [comment]
Fixed in 2.0.0-beta.3
