### ISSUE TITLE
Items still not recognized by new version

### ISSUE THREAD

**Issue by MediEvilHero** [currency-cop/currency-cop#37]
Here's a few I tested:
- Essences (tried both in the special tab and in the regular tab);
- Maps (any rarity, in regular tab);
- Uniques with abyssal sockets;
- Gems (with quality).

**Comment by nijikokun** [comment]
Related to #34

**Comment by MediEvilHero** [comment]
Update for release of 2.0.0-beta.4
Items that still remain unrecognized:
- Maps;
- Uniques with Abyss sockets.

**Comment by nijikokun** [comment]
.5 should cure this issue at least (maps)
