### ISSUE TITLE
Updating Portfolio does not update Portfolio

### ISSUE THREAD

**Issue by Kingpool7** [currency-cop/currency-cop#38]
What I did
1) Created new Portfolio - linked it to my cash tab - works
2) Updating Portfolio, removed cash tab, linked essence tab - no essences, still cash
3) Updating Portfolio, removed essence link, added divination card link - no divination cards, but essences and cash

~~Also, I can't find delete Portfolio button?~~

**Comment by MediEvilHero** [comment]
Because there's no delete Portfolio button yet.

**Comment by Kingpool7** [comment]
Thank you for answer. I thought maybe I just can't find it :).

I'm patient and can wait.

**Comment by nijikokun** [comment]
Fixed! https://github.com/currency-cop/currency-cop/releases/tag/v2.0.0-beta.8
