### ISSUE TITLE
Price discrepancy

### ISSUE THREAD

**Issue by MediEvilHero** [currency-cop/currency-cop#40]
There are a few items that have their prices out of line, for no particular reason.
One that I found so far was Tabula Rasa (not modified in any way) (image: https://i.imgur.com/wfGHTM1.png). Price on poe.ninja was 16 c at the time of writing this.

**Comment by nijikokun** [comment]
Is there a variant on poe.ninja that has a higher amount? Sometimes it happens :(

**Comment by nijikokun** [comment]
Fixed! https://github.com/currency-cop/currency-cop/releases/tag/v2.0.0-beta.8
