### ISSUE TITLE
"Houston, we have a problem"

### ISSUE THREAD

**Issue by diggtrap** [currency-cop/currency-cop#42]
After pasting my ID it simply cuts to this message. Logout button does nothing and I have to close the program. Version 2.0

**Comment by diggtrap** [comment]
Checked previous issue that was closed, but it does not help me.

**Comment by nijikokun** [comment]
Can you do the same as mentioned here? https://github.com/currency-cop/currency-cop/issues/39#issuecomment-385589646

**Comment by nijikokun** [comment]
Should be fixed
