### ISSUE TITLE
Initialization fails due to un-started league (Flashback Event)

### ISSUE THREAD

**Issue by WilliamElder** [currency-cop/currency-cop#44]
Currency cop stops mid-initialization since it can't find item rates for the new league (which can be viewed in the POE client and exists in the POE API, but doesn't exist on poe.ninja yet).

Though this issue will auto-resolve in one day now, it will probably be an issue next time a race event happens.

Some suggested fixes would be to only fetch data for leagues that the player has characters in or to only check leagues that are available on poe.ninja, though the former would probably bug out a few hours after the start of the league (or until poe.ninja updates). But it's your application, so it's your call.

**Comment by nijikokun** [comment]
It won't work for events, plan is to remove events.
