### ISSUE TITLE
Failed to obtain fragment item rates for Flashback Event (BRE003) league

### ISSUE THREAD

**Issue by carncarn** [currency-cop/currency-cop#46]

**Comment by atb26** [comment]
![image](https://user-images.githubusercontent.com/2751639/39786837-57672d08-531a-11e8-9b30-57c589d92372.png)
I'm getting this error too, to expand - Currency Cop can't find these item rates, so fails completely and doesn't let the user continue - even if the user doesn't have any interest in this league.

Per https://github.com/currency-cop/currency-cop/issues/39#issuecomment-385589646 I logged in and out of the PoE website to get a new Session ID, and received a similar error message (this time for currency item rates)

**Comment by nijikokun** [comment]
It won't work for the flashback event.

**Comment by nijikokun** [comment]
Fixed in https://github.com/currency-cop/currency-cop/commit/8942fce4233a0ad0aa3f5f789e56c9bddb96b413
