### ISSUE TITLE
CurrencyCop doesn't recognize links on the items

### ISSUE THREAD

**Issue by MediEvilHero** [currency-cop/currency-cop#49]
Got a few 5/6 links in my tabs none of them are recognized as having those links.

**Comment by MediEvilHero** [comment]
Examples: https://i.imgur.com/4O1pIeI.png & https://i.imgur.com/1KNRkc4.png

**Comment by nijikokun** [comment]
![image](https://user-images.githubusercontent.com/198276/40101838-8962c0be-589d-11e8-8544-e8badae5b87f.png)

Will be fixed in the next version :)

**Comment by nijikokun** [comment]
Fixed in 2.0.0-beta.7 https://github.com/currency-cop/currency-cop/issues/34#issuecomment-389464023
