### ISSUE TITLE
The price of tabula is insane

### ISSUE THREAD

**Issue by vhoanghac** [currency-cop/currency-cop#52]
https://i.imgur.com/dDojVAS.png

91 Chaos.

**Comment by vhoanghac** [comment]
https://i.imgur.com/TKMNIMH.png

Wrong prices...

**Comment by Wheels37** [comment]
Not a project contributor, but it looks like all the data is just getting pulled from the poe.ninja api, if the prices are wrong there (low confidence on tabulas, some gems, but ridiculously high prices) it'll mess up the prices in currency cop.

If the api lists a confidence value, sorting out low confidence might fix this issue

**Comment by nijikokun** [comment]
It has been fixed! https://github.com/currency-cop/currency-cop/releases/tag/v2.0.0-beta.8
