### ISSUE TITLE
Cant Delete Portfolio

### ISSUE THREAD

**Issue by BrentAureli** [currency-cop/currency-cop#54]
If a portfolio is added by mistake, no option that I can find to delete it.

**Comment by afdevries** [comment]
I have a similar issue where I cannot delete nor can I select the portfolio I want to remove. It is the first portfolio I created but never finished setting up.

Sorry to hijack this issue to ask this question, but is there a way to remove it from somewhere outside of the UI perhaps some config file?

**Comment by MediEvilHero** [comment]
There is currently no way to remove the portfolio inside the UI. Can't comment on afdervies' second question though. The only way I know to delete it is by re-installing + deleting CC folder in Roaming.

**Comment by f0lie** [comment]
I really wonder how there isn't a delete button. I know I should be appreciative of free and useful software but still...

Just go to %appdata% then go to the currency-cop folder. Delete portfolio.db and you can start over. The db is in plain text so you can edit with notepad but it's not human useable (giant json file).

**Comment by leet0rz** [comment]
So many futures missing or being bugged with this program atm, its unfortunate, it could be a really really good program with good coding.

**Comment by nijikokun** [comment]
Fixed! https://github.com/currency-cop/currency-cop/releases/tag/v2.0.0-beta.8
