### ISSUE TITLE
After transferring my league stuff to Standard, there seems to be a few inconsistencies

### ISSUE THREAD

**Issue by MediEvilHero** [currency-cop/currency-cop#55]
1. Vessel of Vinktar & Rumi's Concoction. Despite having just regular Vessel of Vinktar & Rumi's Concoction, CurrencyCop displays them as legacy: https://i.imgur.com/jxn89M8.png & https://i.imgur.com/67t15kQ.png
2. Impresence mismatch. I had a fire Impresence in my tab, however CurrencyCop displayed it as chaos one: https://i.imgur.com/tZKDKT6.png & https://i.imgur.com/oJB6LJe.png

**Comment by nijikokun** [comment]
Yes, I have this fixed locally, working on updating the build process so it should be fixed shortly!

**Comment by nijikokun** [comment]
> Impresence mismatch. I had a fire Impresence in my tab, however CurrencyCop displayed it as chaos one: https://i.imgur.com/tZKDKT6.png & https://i.imgur.com/oJB6LJe.png

I've never had these so this might actually still be a problem...
