### ISSUE TITLE
Suspend causes auto-refresh to stop

### ISSUE THREAD

**Issue by dyfrgi** [currency-cop/currency-cop#56]
Release 2.0.0-7.

A suspend-resume cycle causes auto-refresh to stop working. I haven't tested other reasons for network connection being lost. The workaround I'm using is to restart Currency Cop after a resume.

**Comment by nijikokun** [comment]
That's quite an interesting case. I'll see about adding network checks in to pause requests until reconnection to prevent that.

**Comment by nijikokun** [comment]
This should be fixed in [beta.10](https://github.com/currency-cop/currency-cop/releases/tag/2.0.0-beta.10)
