### ISSUE TITLE
Currency cop not receiving data from poeninja

### ISSUE THREAD

**Issue by viper949** [currency-cop/currency-cop#59]
Hello I have used Currency Cop before and love it! The issue I (and maybe others) am having currently is that when i log in it tried to fetch data and is unable to do so from poeninja. I found out where the log files are from one of the other issues which is how i know this. Here is the error:

[16:24:22] [ERROR] [API] Request sent to [http://api.poe.ninja/api/Data/GetCurrencyOverview], no response received: undefined

**Comment by viper949** [comment]
did you just close this without looking at it? lol

the issue is on two separate computers so I'm not sure what the issue is

**Comment by nijikokun** [comment]
It should be fixed in newer releases, are you still getting it?

**Comment by nijikokun** [comment]
It was closed via commit, so the commit has the fixes for this issue

**Comment by viper949** [comment]
ah ok thank you I will try it after work (in about an hour) thanks!
