### ISSUE TITLE
Why no map estimate

### ISSUE THREAD

**Issue by Clockworkx** [currency-cop/currency-cop#62]
Hey,
Can you also include map estimates? A chaos estimate of our maps tab
Also, you could give far more statistics, such as which items have been added in a certain tab after last automatic update and many many more. Concerning maps for example, you could give a red tier map counter, and then we can check how well we sustain, if we see how many got added after last automatic update.

Kind Regards

**Comment by nijikokun** [comment]
Until GGG has an API for the map tab I cannot. To see a symptom of this that GGG also experiences you can view your stashes on your characters on the website, and see the same issue. None of the map tabs will show maps.

**Comment by nijikokun** [comment]
Closing until GGG provides an API
