### ISSUE TITLE
History count only 5?

### ISSUE THREAD

**Issue by efefefefefef** [currency-cop/currency-cop#68]
I would like to see day by day my progress, can we get unlimited history?

**Comment by nijikokun** [comment]
History is capped to 24 items, and the app only shows 5.

In a future release, there will be daily aggregates which will be displayed in various ways (numerical, and charted)

**Comment by efefefefefef** [comment]
Awesome sounds good! It's definitely my number 1 feature request, so great to see it on the backlog.

**Comment by nijikokun** [comment]
Going to close this seeing as there is movement around #64
