### ISSUE TITLE
Stuck at Gathering Prices & Tabs (Standard - unique_accessory)

### ISSUE THREAD

**Issue by Kajean** [currency-cop/currency-cop#71]
Hi, I downloaded the newest version of Currency Cop on my lap top that never had it installed before and it's just stuck on "Gathering Prices & Tabs (Standard - unique_accessory)" when I start it up.

I suspect there's probably a bug but there also could just be so many standard tabs on my account that it takes forever. I highly suggest not processing standard league information by default.

**Comment by nijikokun** [comment]
Can you better define `forever`?

Can you access poe.ninja?

Is your firewall blocking the application?

**Comment by Kajean** [comment]
I can access poe.ninja just fine on this network and laptop. Sorry, I don't have a good measurement for how long I waited. I waited a really long time though. At least 10 minutes before I got impatient and stopped it. I can try to just leave it running over night to see if it ever completes.

**Comment by nijikokun** [comment]
The other thing is you can post your logs (found in `%APPDATA%/currency-cop`) to https://gist.github.com then take the url and post it here, with that I will be able to do some debugging as well.

**Comment by Kajean** [comment]
I looked at those logs maybe there is something blocked on my network.

https://gist.github.com/Kajean/14343e8e4b170d03ba44974001b810c1

I can get to pathofexile.com itself fine though. Maybe it blocks certain types of requests. Thanks for trying to help me out.

**Comment by Kajean** [comment]
I'll try to take my laptop home to my home wifi some day and try there.

**Comment by nijikokun** [comment]
It looks like the application doesn't have permissions to create files on your system, try running as administrator

**Comment by Kajean** [comment]
I tried that just now and no luck. I appreciate your help on this though. I am still using Currency Cop on my home PC and my home network without issue so I'm guessing there's probably just some network problem with this connection I use at work. I'm just gonna close this out. Have a good day.

**Comment by nijikokun** [comment]
I see, that would make a lot of sense especially if your work has a firewall
