### ISSUE TITLE
Unusable when poe.ninja API is unavailable

### ISSUE THREAD

**Issue by markusradtke** [currency-cop/currency-cop#73]
Today I wanted to use CurrencyCop to check my value in Incursion Standard League, but the program just displays errors like 'Failed to obtain map item rates for Standard league.'.

I looked through the log and found, that the API doesn't send an answer. But it only fails to send answers for API calls that need data from Standard, but succesfully delivers the data for Incursion Standard.

Now my problem is that I can't check my value for Incursion Standard League, just because poe.ninja doesn't deliver data for the normal Standard League. This isn't logical from my point of view. Is there maybe a solution to get the value estimation from the data that is available, even if not all the data can be requested from the API?

**Comment by nijikokun** [comment]
Do you mind uploading your logs to http://gist.github.com and posting them here?

**Comment by markusradtke** [comment]
Sure: [Log](https://gist.github.com/markusradtke/1382aaa08186e664a425fd659ae4fc4a)

**Comment by nijikokun** [comment]
@markusradtke it appears that poe.ninja has cloudflare captchas enabled on their API which is causing a 403 error. Apparently cloudflare thinks your IP is abusive or malicious. I have contacted the owner of poe.ninja to make them aware of the captcha on their API. Perhaps visit the site and see if there is a captcha you have to do before gaining access.

I also noticed an issue that the urls are the older ones, I will move over to the new ones in the next release

**Comment by markusradtke** [comment]
Interesting. I called the API URLs by hand and also went to the main site and didn't have to fill a captcha.
Maybe I could look into getting a new IP. Don't know why mine should be abusive or malicious.

**EDIT**: It definitely has to do with my IP, with a VPN everything works fine.
**EDIT2**: Now everything works again even without a VPN.

**Comment by nijikokun** [comment]
Awesome!
