### ISSUE TITLE
VirusTotal scan warnings

### ISSUE THREAD

**Issue by itsamemarkus** [currency-cop/currency-cop#75]
I used CurrencyCop in Abyss and thought of using it again now. I checked the current executable with VirusTotal and there are 7 warnings.

https://www.virustotal.com/en/file/6c71c2faf1d7546e0a6a63992461c7356f641ea73d0c93da6840e45e46a54162/analysis/1530570730/
![2018-07-03 00_34_45-window](https://user-images.githubusercontent.com/34944988/42189531-e938b58a-7e58-11e8-9c6e-46d49d365341.png)

Why are they showing up? I don't feel safe installing now, because I can't check all the code or compile myself. In case these are all false positives, is there any way for you to contact AV companies to whitelist CurrencyCop?

**Comment by fluffyCalculator** [comment]
Refer to this https://github.com/currency-cop/currency-cop/issues/70.

**Comment by nijikokun** [comment]
Closing as these are not something I can personally fix, I've submitted the file to the respective antivirus / antimalware companies. This is out of my hands unfortunately.

See #70
