### ISSUE TITLE
Windows client has Mac window controls

### ISSUE THREAD

**Issue by samspot** [currency-cop/currency-cop#8]
On windows 7. Notably the red close button doesn’t function. 

Edit: They are functioning now, so I edited the issue to remove the "non-functioning" part!

**Comment by nijikokun** [comment]
🤔 interesting, anyone else have windows 7 to test on? I use windows 10 and cannot replicate.

It is also equally interesting considering that it doesn't call a OS specific command: https://github.com/currency-cop/currency-cop/blob/master/src/components/App.js#L2185

**Comment by nijikokun** [comment]
Looks like I've found a related issue in the Electron github issues https://github.com/electron/electron/issues/2312

Seems like there are some theories there to look into

**Comment by samspot** [comment]
![image](https://user-images.githubusercontent.com/884268/31797171-fcd1c62c-b4fa-11e7-9420-2770d1e0d863.png)

Update, I tried again (wasn't at my computer when i posted).  The controls are functioning now, but it still has the mac look.  It makes it far less of an issue though.  I'll edit the top post.

**Comment by nijikokun** [comment]
A little update from spending some time doing #6 I have found that the issue is that there are screens where draggable portions overlay the controls and prevent them from working.

**Comment by samspot** [comment]
That explains why it works when I first open the app but not later. Thanks!
