### ISSUE TITLE
I made a small companion Chrome extension.

### ISSUE THREAD

**Issue by Alaricus** [currency-cop/currency-cop#96]
Hey,

I just wanted to give you a heads up. I made a tiny Chrome extension for easy retrieval of the POESESSID.

Git: https://github.com/Alaricus/Currency-Cop-Companion
Chrome Web Store: https://chrome.google.com/webstore/detail/currency-cop-companion/jmbgoafjkdaoiappiglebakolfchnhid

I hope you are ok with me calling it "Currency Cop Companion" and using your icon. If not, please let me know and I'll take it down immediately and rename it and/or find a new icon.

Cheers!

**Comment by nijikokun** [comment]
Awesome!
